{
  "comments": [
    {
      "key": {
        "uuid": "e1ae5ed4_23053aa3",
        "filename": "src/vpp-api/python/vpp_papi/vpp_transport_socket.py",
        "patchSetId": 7
      },
      "lineNbr": 82,
      "author": {
        "id": 1263
      },
      "writtenOn": "2019-12-20T19:31:41Z",
      "side": 1,
      "message": "during",
      "range": {
        "startLine": 82,
        "startChar": 65,
        "endLine": 82,
        "endChar": 70
      },
      "revId": "30ce92700858f9cc0244e874b9c163d1249ad120",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "31a10726_2452a6d3",
        "filename": "src/vpp-api/python/vpp_papi/vpp_transport_socket.py",
        "patchSetId": 7
      },
      "lineNbr": 157,
      "author": {
        "id": 1263
      },
      "writtenOn": "2019-12-20T19:31:41Z",
      "side": 1,
      "message": "I see you believe (and you are probably right) that a single socket object will work; e.g. on a failure, close (line 147) followed by connect (line 90) will make papi work again.\nIn that case, remove this line, so a subsequent connect (line 80) has a chance to succeed.",
      "range": {
        "startLine": 157,
        "startChar": 8,
        "endLine": 157,
        "endChar": 26
      },
      "revId": "30ce92700858f9cc0244e874b9c163d1249ad120",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2",
      "unresolved": true
    }
  ]
}