{
  "comments": [
    {
      "key": {
        "uuid": "8b3abce8_28d48a39",
        "filename": "src/vpp-api/python/vpp_papi/vpp_transport_socket.py",
        "patchSetId": 1
      },
      "lineNbr": 119,
      "author": {
        "id": 1263
      },
      "writtenOn": "2019-06-12T15:25:39Z",
      "side": 1,
      "message": "Here is the source of possible IOError.",
      "range": {
        "startLine": 119,
        "startChar": 14,
        "endLine": 119,
        "endChar": 26
      },
      "revId": "5177967a2b127b56d4ecf56ff75be7adf6a11a47",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2",
      "unresolved": true
    }
  ]
}