{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "edd4a525_0a08b6cc",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 9
      },
      "lineNbr": 0,
      "author": {
        "id": 361
      },
      "writtenOn": "2024-02-13T15:03:12Z",
      "side": 1,
      "message": "Looks good, thank you very much! Can you rebase it? I\u0027ll merged it once verified.",
      "revId": "cf5fe6c87f3ede0b7e88cfc8c852f43f52809650",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "3dad8881_894f7821",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 9
      },
      "lineNbr": 0,
      "author": {
        "id": 3059
      },
      "writtenOn": "2024-02-14T14:31:12Z",
      "side": 1,
      "message": "Hi Benoit,\n\nI did a rebase.\n\nBut UT fails with the following error\n\n   File \"/w/workspace/vpp-verify-master-ubuntu2004-x86_64/test/test_ikev2.py\", line 977, in verify_ike_sas_v2\n12:31:25     self.assertEqual(self.sa.profile_name, sa.profile_name)\n12:31:25 AttributeError: \u0027IKEv2SA\u0027 object has no attribute \u0027profile_name\u0027\n\nNot sure I understand the logic yet.\nCould you take a look?\n\nThank,\nDenys.",
      "parentUuid": "edd4a525_0a08b6cc",
      "revId": "cf5fe6c87f3ede0b7e88cfc8c852f43f52809650",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2"
    }
  ]
}